[tools]
rojo = { source = "rojo-rbx/rojo", version = "7.4.1" }
wally = { source = "UpliftGames/wally", version = "0.3.2" }
selene = { source = "Kampfkarren/selene", version = "0.27.1" }
stylua = { source = "JohnnyMorganz/stylua", version = "0.20.0" }